export const DARK_THEME = 'DARK_THEME';
export const LIGHT_THEME = 'LIGHT_THEME';

export const GET_DISCOVER_MOVIES = 'GET_DISCOVER_MOVIES';
export const GET_TRENDING_MOVIES = 'GET_TRENDING_MOVIES';
export const GET_NOW_PLAYING_MOVIES = 'GET_NOW_PLAYING_MOVIES';
export const GET_TOP_RATED_MOVIES = 'GET_TOP_RATED_MOVIES';
export const GET_MOVIE_DETAILS = 'GET_MOVIE_DETAILS';
export const GET_MOVIE_IMAGES = 'GET_MOVIE_IMAGES';
export const GET_SIMILAR_MOVIES = 'GET_SIMILAR_MOVIES';
export const GET_MOVIE_PEOPLE = 'GET_MOVIE_PEOPLE';
export const GET_MOVIE_VIDEOS = 'GET_MOVIE_VIDEOS';
export const GET_MOVIE_REVIEWS = 'GET_MOVIE_REVIEWS';
export const GET_MOVIE_LINKS = 'GET_MOVIE_LINKS';

export const GET_DISCOVER_TV = 'GET_DISCOVER_TV';
export const GET_TRENDING_TV = 'GET_TRENDING_TV';
export const GET_NOW_PLAYING_TV = 'GET_NOW_PLAYING_TV';
export const GET_TOP_RATED_TV = 'GET_TOP_RATED_TV';
export const GET_TV_DETAILS = 'GET_TV_DETAILS';
export const GET_TV_IMAGES = 'GET_TV_IMAGES';
export const GET_SIMILAR_TV = 'GET_SIMILAR_TV';
export const GET_TV_PEOPLE = 'GET_TV_PEOPLE';
export const GET_TV_VIDEOS = 'GET_TV_VIDEOS';
export const GET_TV_REVIEWS = 'GET_TV_REVIEWS';
export const GET_TV_LINKS = 'GET_TV_LINKS';

export const GET_FAVORITE_MOVIES = 'GET_FAVORITE_MOVIES';
export const GET_FAVORITE_TV = 'GET_FAVORITE_TV';

export const GET_USER_DETAILS = 'GET_USER_DETAILS';
